[package]
name = "sqlite-hashes"
version = "0.2.0"  # This value is also used in the README.md
description = "Hashing functions for SQLite with aggregation support: MD5, SHA1, SHA256, SHA512"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
repository = "https://github.com/nyurik/sqlite-hashes"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["sqlite", "rusqlite", "hash", "md5", "sha256"]
categories = ["database", "cryptography"]
rust-version = "1.60.0"

[features]
default = ["md5", "sha1", "sha256", "sha512"]
md5 = ["dep:md-5"]
sha1 = ["dep:sha1"]
sha256 = ["dep:sha2"]
sha512 = ["dep:sha2"]

[dependencies]
rusqlite = { version = "0.29.0", features = ["functions"] }

# Digest and all hashing algorithms are using the same crates internally, so should be kept in sync
digest = "0.10.7"
md-5 = { version = "0.10.5", optional = true }
sha1 = { version = "0.10.5", optional = true }
sha2 = { version = "0.10.5", optional = true }

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }
